all:
	rm -rf delay
	gcc -g  -std=c99  ini.c  ini.h vector.h  vector.c connection_base.h  connection_base.c connection_event.h connection_event.c common.h common.c     main.c  -o  delay -lpthread  -lmysqlclient
